<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~
  ~ WSO2 Inc. licenses this file to you under the Apache License,
  ~ Version 2.0 (the "License"); you may not use this file except
  ~ in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<!--<!DOCTYPE assembly [
        <!ELEMENT assembly (formats|includeBaseDirectory|fileSets|dependencySets|files)*>
        <!ELEMENT formats (format)*>
        <!ELEMENT format (#PCDATA)>
        <!ELEMENT includeBaseDirectory (#PCDATA)>
        <!ELEMENT fileSets (fileSet)*>
        <!ELEMENT fileSet (directory|outputDirectory|excludes|includes|fileMode)*>
        <!ELEMENT directory (#PCDATA)>
        <!ELEMENT outputDirectory (#PCDATA)>
        <!ELEMENT excludes (exclude)*>
        <!ELEMENT exclude (#PCDATA)>
        <!ELEMENT includes (include)*>
        <!ELEMENT include (#PCDATA)>
        <!ELEMENT fileMode (#PCDATA)>
        <!ELEMENT dependencySets (dependencySet)*>
        <!ELEMENT dependencySet (outputDirectory|includes|outputFileNameMapping)*>
        <!ELEMENT outputFileNameMapping (#PCDATA)>
        <!ELEMENT files (file)*>
        <!ELEMENT file (source|outputDirectory|fileMode|destName|filtered)*>
        <!ELEMENT source (#PCDATA)>
        <!ELEMENT destName (#PCDATA)>
        <!ELEMENT filtered (#PCDATA)>
        ]>-->
<assembly>
    <id>wso2ei-bin</id>
    <formats>
        <format>zip</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <fileSets>
        <fileSet>
            <directory>../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/components</directory>
            <outputDirectory>wso2mi-${pom.version}/wso2/components</outputDirectory>
            <excludes>
                <exclude>**/eclipse.ini</exclude>
                <exclude>**/*.lock</exclude>
                <exclude>**/.data</exclude>
                <exclude>**/.settings</exclude>
                <exclude>**/org.wso2.carbon.feature.mgt.ui*</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>tmp/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/Owasp.CsrfGuard.Carbon.properties</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/plugins/saxon_*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/conf/tomcat/webapp-classloading-environments.xml</exclude>
                <exclude>**/conf/registry.xml</exclude>
                <exclude>**/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/conf/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/wso2/components/plugins/httpclient_4.3.1.wso2v3.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar</exclude>
                <exclude>**/wso2/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
		        <exclude>**/features/**</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}</directory>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/wso2</exclude>
                <exclude>**/repository/conf/**</exclude>
                <exclude>**/repository/components/**</exclude>
                <exclude>**/wso2/components/**</exclude>
                <exclude>**/lib/**</exclude>
                <exclude>**/bin/**</exclude>
                <exclude>**/conf/axis2/axis2.xml</exclude>
                <exclude>**/conf/axis2/tenant-axis2.xml</exclude>
                <exclude>**/conf/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/user-mgt.xml</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/wso2/components/plugins/saxon*.jar</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/repository/conf/tomcat/catalina-server.xml</exclude>
                <exclude>**/repository/conf/registry.xml</exclude>
                <exclude>**/repository/conf/tomcat/web.xml</exclude>
                <exclude>**/webapp-mode/WEB-INF/web.xml</exclude>
                <exclude>**/repository/components/plugins/httpclient_4.3.1.wso2v3.jar</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-jms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/axis2-transport-sms_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/tomcat/carbon/META-INF/context.xml</exclude>
                <exclude>**/repository/components/plugins/axis2-transport-mail_1.1.1.wso2v2.jar
                </exclude>
                <exclude>**/repository/components/plugins/jsch_0.1.49.wso2v1.jar</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <excludes>
                <exclude>**/wso2</exclude>
                <exclude>**/*.sh</exclude>
                <exclude>**/axis2/axis2.xml</exclude>
                <exclude>**/axis2/tenant-axis2.xml</exclude>
                <exclude>**/synapse.xml</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/services/sample01.aar</exclude>
                <exclude>**/repository/services/version/**</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/registry.xml</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/user-mgt.xml</exclude>
                <exclude>**/repository/conf/etc/logging-bridge.properties</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/lib/endorsed/xalan*.jar</exclude>
                <exclude>**/tomcat/carbon/WEB-INF/web.xml</exclude>
                <exclude>**/tomcat/carbon/META-INF/context.xml</exclude>
                <exclude>**//tomcat/catalina-server.xml</exclude>
                <exclude>**/launch.ini</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/bin</directory>
            <outputDirectory>wso2mi-${pom.version}/bin</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/*.bat</exclude>
                <exclude>**/wrapper.conf</exclude>
                <exclude>build.xml</exclude>
                <exclude>version.txt</exclude>
                <exclude>README.txt</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/bin</outputDirectory>
            <includes>
                <include>**.sh</include>
                <include>**.bat</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/build.xml</include>
                <include>**/carbondump.bat</include>
                <include>**/carbondump.sh</include>
                <include>**/chpasswd.bat</include>
                <include>**/chpasswd.sh</include>
                <include>**/tcpmon.bat</include>
                <include>**/tcpmon.sh</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/build.xml</include>
                <include>**/micro-integrator.bat</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/scripts/</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/bin
            </outputDirectory>
            <includes>
                <include>**/tcpmon.sh</include>
                <include>**/micro-integrator.sh</include>
            </includes>
            <fileMode>755</fileMode>
        </fileSet>


        <fileSet>
            <directory>src/resources/dockerfiles</directory>
            <outputDirectory>wso2mi-${pom.version}/dockerfiles</outputDirectory>
            <excludes>
                <exclude>**/Dockerfile</exclude>
                <exclude>**/.gitkeep</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/resources/tomcat</directory>
            <outputDirectory>wso2mi-${pom.version}/conf/tomcat</outputDirectory>
            <includes>
                <include>**/catalina-server.xml</include>
                <include>**/webapp-classloading-environments.xml</include>
            </includes>
        </fileSet>

        <fileSet>
            <directory>src/conf</directory>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <includes>
                <include>**/cipher-standalone-config.properties</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>
                .../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/identity
            </directory>
            <outputDirectory>
                wso2mi-${pom.version}/conf/identity/
            </outputDirectory>
        </fileSet>

        <fileSet>
            <directory>src/conf/synapse-configs</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/synapse-configs
            </outputDirectory>
            <excludes>
                <exclude>**/empty.txt</exclude>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/lib</directory>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib</outputDirectory>
            <excludes>
                <exclude>**/*.sh</exclude>
                <exclude>**/log4j.properties</exclude>
                <exclude>**/version.txt</exclude>
                <exclude>**/wso2carbon-version.txt</exclude>
                <exclude>**/wso2server.bat</exclude>
                <exclude>**/README.txt</exclude>
                <exclude>**/LICENSE.txt</exclude>
                <exclude>**/release-notes.html</exclude>
                <exclude>**/carbon.xml</exclude>
                <exclude>**/endorsed/xalan*.jar</exclude>
                <exclude>**/endorsed/geronimo-jms_1.1_spec*.jar</exclude>
            </excludes>
        </fileSet>


        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/dropins
            </directory>
            <outputDirectory>wso2mi-${pom.version}/dropins</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>

        <fileSet>
            <directory>src/resources</directory>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib/endorsed</outputDirectory>
            <includes>
                <include>**/saxon9he.jar</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>src/resources</directory>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib/</outputDirectory>
            <includes>
                <include>esapi-2.0.1.jar</include>
            </includes>
        </fileSet>
        <fileSet>
            <directory>target/wso2carbon-core-${carbon.kernel.version}/repository/components/lib
            </directory>
            <outputDirectory>wso2mi-${pom.version}/lib</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>
                target/wso2carbon-core-${carbon.kernel.version}/repository/components/patches
            </directory>
            <outputDirectory>wso2mi-${pom.version}/patches</outputDirectory>
            <excludes>
            </excludes>
        </fileSet>
        <fileSet>
            <directory>src/resources/capps</directory>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/carbonapps</outputDirectory>
            <excludes>
                <exclude>empty.txt</exclude>
            </excludes>
        </fileSet>
    </fileSets>

    <files>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/version.txt</source>
            <outputDirectory>wso2mi-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/wrapper.conf</source>
            <outputDirectory>wso2mi-${pom.version}/bin/yajsw</outputDirectory>
            <destName>wrapper.conf</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/log4j.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>log4j.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/carbon.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/tasks-config.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc/
            </outputDirectory>
        </file>
        <file>
            <source>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/event-broker.xml
            </source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/data-bridge/data-agent-config.xml
            </source>
            <outputDirectory>wso2mi-${pom.version}/conf/data-bridge</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>
                ../p2-profile/target/wso2carbon-core-${carbon.kernel.version}/wso2/conf/rule-engine-config.xml
            </source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/axis2.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/user-mgt.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>user-mgt.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/context.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/tomcat/carbon/MATA-INF</outputDirectory>
            <destName>context.xml</destName>
        </file>

        <file>
            <source>src/conf/web.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/tomcat/carbon/WEB-INF</outputDirectory>
            <destName>web.xml</destName>
        </file>

        <file>
            <source>src/conf/axis2_blocking_client.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf/axis2</outputDirectory>
            <destName>axis2_blocking_client.xml</destName>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/datasources.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>datasources.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/nhttp.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>nhttp.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/access-log.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>access-log.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/internal-apis.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf</outputDirectory>
            <destName>internal-apis.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/jndi.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>jndi.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/logging-config.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/launch.ini</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/etc/logging-bridge.properties</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/conf/etc</outputDirectory>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/passthru-http.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>passthru-http.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/conf/synapse.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>synapse.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <!--File based Synapse registry for Micro EI-->
        <file>
            <source>src/conf/registry.xml</source>
            <outputDirectory>${pom.artifactId}-${pom.version}/repository/deployment/server/synapse-configs/default
            </outputDirectory>
            <filtered>true</filtered>
        </file>

        <file>
            <source>src/conf/synapse-handlers.xml</source>
            <outputDirectory>wso2mi-${pom.version}/conf</outputDirectory>
            <destName>synapse-handlers.xml</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/cipher-text.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-text.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/cipher-tool.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>cipher-tool.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/conf/security/secret-conf.properties</source>
            <outputDirectory>wso2mi-${pom.version}/conf/security</outputDirectory>
            <destName>secret-conf.properties</destName>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/resources/dockerfiles/Dockerfile</source>
            <outputDirectory>wso2mi-${pom.version}/dockerfiles/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>

        <file>
            <source>src/docs/release-notes.xml</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <destName>release-notes.html</destName>
            <fileMode>644</fileMode>
            <filtered>true</filtered>
        </file>
        <file>
            <source>src/LICENSE.txt</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/README.txt</source>
            <outputDirectory>wso2mi-${pom.version}</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>src/resources/updates/product.txt</source>
            <outputDirectory>wso2mi-${pom.version}/updates</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
        <file>
            <source>target/wso2carbon-core-${carbon.kernel.version}/bin/README.txt</source>
            <outputDirectory>wso2mi-${pom.version}/bin/</outputDirectory>
            <filtered>true</filtered>
            <fileMode>644</fileMode>
        </file>
    </files>

    <dependencySets>
        <dependencySet>
            <useProjectArtifact>false</useProjectArtifact>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib</outputDirectory>
            <includes>
                <include>org.wso2.ei:org.wso2.carbon.micro.integrator.server:jar</include>
            </includes>
        </dependencySet>
        <dependencySet>
            <outputDirectory>wso2mi-${pom.version}/repository/deployment/server/axis2modules
            </outputDirectory>
            <includes>
                <include>org.apache.rampart:rampart:mar</include>
            </includes>
        </dependencySet>
        <dependencySet>
            <outputDirectory>wso2mi-${pom.version}/wso2/lib/endorsed</outputDirectory>
            <includes>
                <include>javax.jms:javax.jms-api:jar</include>
            </includes>
        </dependencySet>
    </dependencySets>
</assembly>
